# 02 - Make Prediction
---

### Description:
make_predictions script: should load your saved model generated by the first script, and output a predictions.csv file with your predictions (one prediction per line)

### Sections:
1. Reading in the

In [14]:
# Importing all the related libraries
import pickle
import pandas as pd

In [15]:
model_file = r"03_model_binary.pickle"
testing_data = r"data/test_potus_by_county.csv"

In [21]:
# Loading in the model and the data
trained_model = pickle.load(open(model_file, 'rb'))
testing_df = pd.read_csv(testing_data)

In [22]:
testing_df

,Total population,Median age,% BachelorsDeg or higher,Unemployment rate,Per capita income,Total households,Average household size,% Owner occupied housing,% Renter occupied housing,% Vacant housing,Median home value,Population growth,House hold growth,Per capita income growth
0,695751,34.692593,19.896296,10.651852,25624.074074,248724,2.816296,42.044444,25.755556,32.207407,179329.851852,-0.295185,-0.239259,2.62963
1,28759,37.300000,13.100000,14.300000,15978.000000,10447,2.450000,58.700000,21.200000,20.100000,79052.000000,-0.230000,-0.100000,0.71000
2,10926,36.200000,9.500000,17.000000,12847.000000,3749,2.480000,58.700000,20.100000,21.200000,72014.000000,-0.770000,-0.750000,1.05000
3,13266,40.900000,10.900000,20.900000,15340.000000,5624,2.340000,59.800000,13.900000,26.300000,68596.000000,-0.610000,-0.450000,0.73000
4,42841,37.000000,16.300000,22.600000,15369.000000,17046,2.480000,54.500000,28.200000,17.200000,74130.000000,-0.740000,-0.570000,0.76000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,8640,44.400000,22.700000,3.900000,22937.000000,3557,2.410000,49.500000,17.000000,33.500000,245091.000000,4.330000,4.490000,1.58000
1897,41019,35.200000,17.800000,7.400000,25548.000000,15939,2.530000,66.400000,21.700000,11.900000,170417.000000,1.170000,1.370000,2.20000
1898,21330,31.200000,15.900000,7.800000,21023.000000,7628,2.750000,63.100000,20.900000,16.000000,154416.000000,1.170000,1.360000,1.65000
1899,7966,41.800000,18.800000,8.900000,22564.000000,3240,2.400000,65.500000,23.400000,11.100000,133226.000000,-0.280000,-0.140000,2.07000
1900,7160,43.600000,15.400000,6.000000,20567.000000,2905,2.340000,63.300000,17.600000,19.100000,119712.000000,0.730000,0.930000,2.07000